[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "QIQSS-Code"
authors = [{name = "Claude Rohrbacher", email = "claude.rohrbacher@usherbrooke.ca"}]
dynamic = ["version", "description"]
